name: Build and Package Jar

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Upload jar artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-app-jar
        path: target/*.jar
